### ISSUE TITLE
Source folders generated at incorrect location

### ISSUE THREAD

**Issue by KingHanWen** [ashdavies/data-binding#4]
Source folders generated at incorrect location
Warning:Folder C:\Users\Administrator\AndroidStudioProjects\Test\app\build\data-binding-info\debug
Warning:Folder C:\Users\Administrator\AndroidStudioProjects\Test\app\build\data-binding-info\androidTest\debug
Information:3rd-party Gradle plug-ins may be the cause

Looking forward to your reply

**Comment by ashdavies** [comment]
Hi @KingHanWen 
I'm afraid I can't tell much from your report, the project is barebones only demonstrating how the data binding api can be used, ie. very few 3rd party plugins included.

**Comment by fyunli** [comment]
@KingHanWen 
you can add this to your app build.gradle to fix it.

// fix for dataBinder: Source folders generated at incorrect location
android.applicationVariants.all { variant ->
    def variantName = variant.name.capitalize()
    def inputDir    = "${buildDir}/intermediates/classes/${variant.dirName}"
    def sourceDir   = "${buildDir}/generated/source/dataBinding/${variant.dirName}"
    def copyTask    = tasks.create(name: "dataBindingFix${variantName}", type: Copy) {
        from inputDir
        into sourceDir
        include '**/*.java'
    }
    tasks["generate${variantName}Sources"].dependsOn copyTask
    variant.addJavaSourceFoldersToModel new File(sourceDir)
}
