### ISSUE TITLE
Data binding in library 

### ISSUE THREAD

**Issue by patelakshay13890** [ashdavies/data-binding#6]
Hey developers,  How can I use data  binding  in  my application because  I am  new to  data  binding  concept ?
I have  an  application  module  and  one  android  lib. Module  which  has  all the  entites  those  are used in app module l..
So how  can I  use  data binding  in  my  app  with  lib. Module..﻿
Which also include  dynamic inflation of view  based on parameter in some of the  entities in library module ﻿

**Comment by ashdavies** [comment]
The data binding library has been updated a fair bit since I made this repository, please check out the Android documentation along with recent examples for more information.
https://developer.android.com/topic/libraries/data-binding/index.html
